-- Kisan Setu PostgreSQL schema

CREATE TABLE IF NOT EXISTS farmers (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name TEXT NOT NULL,
    mobile TEXT NOT NULL UNIQUE,
    email TEXT,
    state TEXT NOT NULL,
    district TEXT NOT NULL,
    village TEXT NOT NULL,
    land_area DOUBLE PRECISION NOT NULL,
    crop TEXT NOT NULL,
    password_hash TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS centres (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    state TEXT NOT NULL,
    district TEXT NOT NULL,
    location TEXT NOT NULL,
    capacity INTEGER NOT NULL,
    status TEXT NOT NULL DEFAULT 'Active',
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    CONSTRAINT centres_name_unique UNIQUE (name)
);

INSERT INTO centres (name, state, district, location, capacity, status)
VALUES
    ('Kisan Seva Centre - Patna', 'Bihar', 'Patna', 'Danapur', 100, 'Active'),
    ('Kisan Seva Centre - Muzaffarpur', 'Bihar', 'Muzaffarpur', 'Muzaffarpur City', 80, 'Active'),
    ('Kisan Seva Centre - Gaya', 'Bihar', 'Gaya', 'Gaya City', 120, 'Active'),
    ('Government Procurement Centre - Ambala', 'Haryana', 'Ambala', 'Ambala City', 500, 'Active'),
    ('Government Procurement Centre - Bhiwani', 'Haryana', 'Bhiwani', 'Bhiwani City', 400, 'Active'),
    ('Government Procurement Centre - Hisar', 'Haryana', 'Hisar', 'Hisar City', 500, 'Active'),
    ('Government Procurement Centre - Karnal', 'Haryana', 'Karnal', 'Karnal City', 450, 'Active'),
    ('Government Procurement Centre - Kurukshetra', 'Haryana', 'Kurukshetra', 'Thanesar', 350, 'Active'),
    ('Government Procurement Centre - Rohtak', 'Haryana', 'Rohtak', 'Rohtak City', 400, 'Active'),
    ('Government Procurement Centre - Sirsa', 'Haryana', 'Sirsa', 'Sirsa City', 300, 'Active'),
    ('Government Procurement Centre - Sonipat', 'Haryana', 'Sonipat', 'Sonipat City', 450, 'Active'),
    ('Government Procurement Centre - Yamunanagar', 'Haryana', 'Yamunanagar', 'Yamunanagar City', 350, 'Active')
ON CONFLICT (name) DO NOTHING;

CREATE TABLE IF NOT EXISTS bookings (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id TEXT NOT NULL UNIQUE,
    farmer_id INTEGER NOT NULL REFERENCES farmers(id),
    centre_id INTEGER NOT NULL REFERENCES centres(id),
    crop TEXT NOT NULL,
    booking_date TEXT NOT NULL,
    time_slot TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'Confirmed',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS queue_entries (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id INTEGER NOT NULL REFERENCES bookings(id),
    farmer_id INTEGER NOT NULL REFERENCES farmers(id),
    centre_id INTEGER NOT NULL REFERENCES centres(id),
    token_number INTEGER NOT NULL,
    queue_position INTEGER NOT NULL,
    estimated_wait_minutes INTEGER NOT NULL DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'Waiting',
    quality_check TEXT NOT NULL DEFAULT 'Pending',
    weighing_check TEXT NOT NULL DEFAULT 'Pending',
    procurement_check TEXT NOT NULL DEFAULT 'Pending',
    payment_check TEXT NOT NULL DEFAULT 'Pending',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
